### PR TITLE
fix: Stop cloning as soon as namespace is reached

### LINKED ISSUE #8: dm creates huge files with patched dplyr
The call `dm::dm(cars1 = head(cars,2), cars2 = tail(cars,2))` creates 5 files from 15 to 35 MB in a fresh session, the dplyr calls cannot need so much data

### PR DESCRIPTION
**Pull request by krlmlr**
Closes #8.

``` r
Sys.setenv(COLLECTOR_PATH = ".")
library(comperes)

get_matchups(ncaa2005)
#> # A widecr object:
#> # A tibble: 40 × 5
#>     game player1 score1 player2 score2
#>    <int> <chr>    <int> <chr>    <int>
#>  1     1 Duke         7 Duke         7
#>  2     1 Duke         7 Miami       52
#>  3     1 Miami       52 Duke         7
#>  4     1 Miami       52 Miami       52
#>  5     2 Duke        21 Duke        21
#>  6     2 Duke        21 UNC         24
#>  7     2 UNC         24 Duke        21
#>  8     2 UNC         24 UNC         24
#>  9     3 Duke         7 Duke         7
#> 10     3 Duke         7 UVA         38
#> # ℹ 30 more rows

callr::r(function() {
  Sys.setenv(COLLECTOR_PATH = "")
  data <- qs::qread("3-mutate.qs")

  get("mutate", data$env)
})
#> function(.data, ...) {
#>   UseMethod("mutate")
#> }
#> <bytecode: 0x105b7c700>
#> <environment: namespace:dplyr>
```

<sup>Created on 2024-04-19 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

**Comment by krlmlr** [comment]
I haven't checked the original problem, but chances are very high that this is a fix.

**Comment by moodymudskipper** [comment]
Oh I see, namespaces don't have a name attribute.
I'm not sure this is quite right yet though, because here we don't serialize anything from the global env, because it has a `env_name()`, should we add an exception ?

**Comment by moodymudskipper** [comment]
I can take it from here

**Comment by moodymudskipper** [comment]
> I haven't checked the original problem, but chances are very high that this is a fix.

It is!

**Pull request merged**
